### ISSUE TITLE
Add lvmifusim to lvmcore

### ISSUE THREAD

**Issue by maxhaeberle** [sdss/lvmcore#2]
To look deeper into stellar contamination issues (i.e. how many stars fall into a fiber within the IFU), I need confirmed coordinates for the position of the fibers/microlenses within the focal plane. The IFU function of lvmifusim returns these values, but it would be good to add these functions to the lvmcore, if the positions are final.

**Comment by ndrory** [comment]
Max,

the nominal values returned by the IFU object will eventually be replaced by lab-measured as built values for the real IFU and be stored in lvmcore (or some database).

	N.

> On May 12, 2021, at 10:51 AM, max-haeberle ***@***.***> wrote:
> 
> 
> To look deeper into stellar contamination issues (i.e. how many stars fall into a fiber within the IFU), I need confirmed coordinates for the position of the fibers/microlenses within the focal plane. The IFU function of lvmifusim returns these values, but it would be good to add these functions to the lvmcore, if the positions are final.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- Niv Drory —
McDonald Observatory / Dept. of Astronomy
The University of Texas at Austin
Tel: +1 512 471 6197
http://www.as.utexas.edu/~drory

**Comment by maxhaeberle** [comment]
Thanks!
So far the values from the IFU objects are the best estimates we have, correct?

**Comment by ndrory** [comment]
Yes, they are the nominal values. 

The IFU object will eventually return as-built values. It will remain the responsible entity to get you whatever the current best estimate is.

If you are looking at stellar densities for the dark patches for sky, I think you don't need the fibers at all, you just need the stellar density within the area of the (sky) IFU. It does not matter if the stars are in fibers or not.

For the main survey, we will eventually need a code that does create a catalog of stars in each science fiber, so it will still be useful in the future.

Lastly, please move this thread to lvm-data or lvm-science, and away from github lists. These are not being archived by us and are outside of our control.

	N.

> On May 12, 2021, at 11:01 AM, max-haeberle ***@***.***> wrote:
> 
> 
> Thanks!
> So far the values from the IFU objects are the best estimates we have, correct?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- Niv Drory —
McDonald Observatory / Dept. of Astronomy
The University of Texas at Austin
Tel: +1 512 471 6197
http://www.as.utexas.edu/~drory

**Comment by maxhaeberle** [comment]
Ok thanks!
I will use a lvm mailing-list if further question arise.
